// AUTO-GENERATED by scripts/generate_ts_enums.py — DO NOT EDIT.
// Source of truth: services/api/src/saige_api/models/enums.py

export const ActorType = {
  USER: "user",
  SYSTEM: "system",
  AGENT: "agent",
  WORKER: "worker",
} as const;
export type ActorType = (typeof ActorType)[keyof typeof ActorType];

export const AgentRunStatus = {
  RUNNING: "running",
  AWAITING_CONFIRMATION: "awaiting_confirmation",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  TIMED_OUT: "timed_out",
  MAX_ITERATIONS: "max_iterations",
  CANCELLED: "cancelled",
} as const;
export type AgentRunStatus = (typeof AgentRunStatus)[keyof typeof AgentRunStatus];

export const AgentStepType = {
  PLAN: "plan",
  TOOL_CALL: "tool_call",
  OBSERVATION: "observation",
  FINAL: "final",
} as const;
export type AgentStepType = (typeof AgentStepType)[keyof typeof AgentStepType];

export const AuditAction = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FILE_UPLOAD: "FILE_UPLOAD",
  FILE_DOWNLOAD: "FILE_DOWNLOAD",
  FILE_DELETE: "FILE_DELETE",
  FILE_RESTORE: "FILE_RESTORE",
  FILE_RENAME: "FILE_RENAME",
  FILE_MOVE: "FILE_MOVE",
  AI_QUERY: "AI_QUERY",
  AI_DOCUMENT_ACCESS: "AI_DOCUMENT_ACCESS",
  AGENT_EXECUTION: "AGENT_EXECUTION",
  OAUTH_CONNECT: "OAUTH_CONNECT",
  OAUTH_DISCONNECT: "OAUTH_DISCONNECT",
  SECURITY_EVENT: "SECURITY_EVENT",
  DATA_EXPORT: "DATA_EXPORT",
} as const;
export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const ChunkingStrategy = {
  RECURSIVE: "recursive",
  DOCUMENT_AWARE: "document_aware",
  PAGE_AWARE: "page_aware",
  SEMANTIC: "semantic",
} as const;
export type ChunkingStrategy = (typeof ChunkingStrategy)[keyof typeof ChunkingStrategy];

export const ClientPlatform = {
  WEB: "web",
  ANDROID: "android",
  IOS: "ios",
  API: "api",
} as const;
export type ClientPlatform = (typeof ClientPlatform)[keyof typeof ClientPlatform];

export const ConversationScope = {
  FILE: "file",
  FILES: "files",
  FOLDER: "folder",
  COLLECTION: "collection",
  VAULT: "vault",
} as const;
export type ConversationScope = (typeof ConversationScope)[keyof typeof ConversationScope];

export const DataSource = {
  SYSTEM: "system",
  AI: "ai",
  USER: "user",
} as const;
export type DataSource = (typeof DataSource)[keyof typeof DataSource];

export const DocumentType = {
  IDENTITY: "identity",
  EDUCATION: "education",
  EMPLOYMENT: "employment",
  SALARY: "salary",
  BANKING: "banking",
  TAX: "tax",
  INSURANCE: "insurance",
  FINANCE: "finance",
  MEDICAL: "medical",
  LEGAL: "legal",
  TRAVEL: "travel",
  CERTIFICATE: "certificate",
  RESUME: "resume",
  JOB_DESCRIPTION: "job_description",
  PERSONAL: "personal",
  WORK: "work",
  PROJECT: "project",
  IMAGE: "image",
  OTHER: "other",
  UNCLASSIFIED: "unclassified",
} as const;
export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];

export const EmbeddingStatus = {
  PENDING: "pending",
  INDEXED: "indexed",
  FAILED: "failed",
  STALE: "stale",
} as const;
export type EmbeddingStatus = (typeof EmbeddingStatus)[keyof typeof EmbeddingStatus];

export const ExtractionMethod = {
  NATIVE_TEXT: "native_text",
  OCR: "ocr",
} as const;
export type ExtractionMethod = (typeof ExtractionMethod)[keyof typeof ExtractionMethod];

export const FileVisibility = {
  PRIVATE: "private",
} as const;
export type FileVisibility = (typeof FileVisibility)[keyof typeof FileVisibility];

export const JobStatus = {
  QUEUED: "queued",
  RUNNING: "running",
  RETRY_SCHEDULED: "retry_scheduled",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  DEAD_LETTERED: "dead_lettered",
  CANCELLED: "cancelled",
} as const;
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];

export const JobType = {
  DOCUMENT_PROCESSING: "document_processing",
  OCR: "ocr",
  EMBEDDING_GENERATION: "embedding_generation",
  METADATA_EXTRACTION: "metadata_extraction",
  THUMBNAIL_GENERATION: "thumbnail_generation",
  DRIVE_SYNC: "drive_sync",
  FILE_INTEGRITY_CHECK: "file_integrity_check",
  AI_INDEXING: "ai_indexing",
} as const;
export type JobType = (typeof JobType)[keyof typeof JobType];

export const MessageRole = {
  USER: "user",
  ASSISTANT: "assistant",
  SYSTEM: "system",
  TOOL: "tool",
} as const;
export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];

export const MessageStatus = {
  PENDING: "pending",
  STREAMING: "streaming",
  COMPLETED: "completed",
  FAILED: "failed",
  CANCELLED: "cancelled",
} as const;
export type MessageStatus = (typeof MessageStatus)[keyof typeof MessageStatus];

export const NotificationType = {
  PROCESSING_COMPLETE: "processing_complete",
  PROCESSING_FAILED: "processing_failed",
  UPLOAD_COMPLETE: "upload_complete",
  SYNC_COMPLETE: "sync_complete",
  AI_INDEXING_COMPLETE: "ai_indexing_complete",
  SECURITY_EVENT: "security_event",
  EXPIRY_REMINDER: "expiry_reminder",
} as const;
export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];

export const ProcessingStatus = {
  PENDING: "pending",
  QUEUED: "queued",
  PROCESSING: "processing",
  READY: "ready",
  FAILED: "failed",
  UNSUPPORTED: "unsupported",
} as const;
export type ProcessingStatus = (typeof ProcessingStatus)[keyof typeof ProcessingStatus];

export const SearchMode = {
  EXACT: "exact",
  FULL_TEXT: "full_text",
  SEMANTIC: "semantic",
  HYBRID: "hybrid",
} as const;
export type SearchMode = (typeof SearchMode)[keyof typeof SearchMode];

export const SecuritySeverity = {
  INFO: "info",
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  CRITICAL: "critical",
} as const;
export type SecuritySeverity = (typeof SecuritySeverity)[keyof typeof SecuritySeverity];

export const StageStatus = {
  NOT_REQUIRED: "not_required",
  PENDING: "pending",
  PROCESSING: "processing",
  COMPLETED: "completed",
  FAILED: "failed",
  SKIPPED_BY_POLICY: "skipped_by_policy",
} as const;
export type StageStatus = (typeof StageStatus)[keyof typeof StageStatus];

export const StorageConnectionStatus = {
  ACTIVE: "active",
  NEEDS_REAUTH: "needs_reauth",
  DISCONNECTED: "disconnected",
  ERROR: "error",
} as const;
export type StorageConnectionStatus = (typeof StorageConnectionStatus)[keyof typeof StorageConnectionStatus];

export const StorageProviderKind = {
  GOOGLE_DRIVE: "google_drive",
} as const;
export type StorageProviderKind = (typeof StorageProviderKind)[keyof typeof StorageProviderKind];

export const SummaryType = {
  SHORT: "short",
  DETAILED: "detailed",
  KEY_POINTS: "key_points",
  ACTION_ITEMS: "action_items",
  IMPORTANT_DATES: "important_dates",
} as const;
export type SummaryType = (typeof SummaryType)[keyof typeof SummaryType];

export const SyncChangeType = {
  CREATED: "created",
  MODIFIED: "modified",
  MOVED: "moved",
  RENAMED: "renamed",
  TRASHED: "trashed",
  RESTORED: "restored",
  DELETED: "deleted",
} as const;
export type SyncChangeType = (typeof SyncChangeType)[keyof typeof SyncChangeType];

export const SyncStatus = {
  QUEUED: "queued",
  RUNNING: "running",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
} as const;
export type SyncStatus = (typeof SyncStatus)[keyof typeof SyncStatus];

export const SyncType = {
  FULL: "full",
  INCREMENTAL: "incremental",
} as const;
export type SyncType = (typeof SyncType)[keyof typeof SyncType];

export const TagStatus = {
  SUGGESTED: "suggested",
  CONFIRMED: "confirmed",
  REJECTED: "rejected",
} as const;
export type TagStatus = (typeof TagStatus)[keyof typeof TagStatus];

export const ToolCallStatus = {
  PENDING: "pending",
  AWAITING_CONFIRMATION: "awaiting_confirmation",
  APPROVED: "approved",
  REJECTED: "rejected",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  DENIED: "denied",
} as const;
export type ToolCallStatus = (typeof ToolCallStatus)[keyof typeof ToolCallStatus];

export const UserStatus = {
  ACTIVE: "active",
  DISABLED: "disabled",
} as const;
export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];
