"""Generate TypeScript enums from the backend's Python enums.

The Python enums in saige_api.enums are the single source of truth.
CI runs this script and fails if the committed output differs.

Usage: uv run python scripts/generate_ts_enums.py
"""

from __future__ import annotations

import enum
import inspect
import re
import sys
from pathlib import Path

from saige_api import enums

OUTPUT = Path(__file__).resolve().parents[1] / "packages" / "types" / "src" / "enums.gen.ts"


def _const_name(member: str) -> str:
    return re.sub(r"[^A-Z0-9_]", "_", member.upper())


def render() -> str:
    lines = [
        "// AUTO-GENERATED by scripts/generate_ts_enums.py — DO NOT EDIT.",
        "// Source of truth: services/api/src/saige_api/enums.py",
        "",
    ]
    classes = [
        obj
        for _, obj in inspect.getmembers(enums, inspect.isclass)
        if issubclass(obj, enum.StrEnum)
        and obj is not enum.StrEnum
        and obj.__module__ == enums.__name__
    ]
    for cls in sorted(classes, key=lambda c: c.__name__):
        lines.append(f"export const {cls.__name__} = {{")
        lines.extend(f'  {_const_name(m.name)}: "{m.value}",' for m in cls)
        lines.append("} as const;")
        name = cls.__name__
        lines.append(f"export type {name} = (typeof {name})[keyof typeof {name}];")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            sys.stderr.write(f"{OUTPUT} is out of date. Run scripts/generate_ts_enums.py\n")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    sys.stdout.write(f"Wrote {OUTPUT}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
